LIBMTWIST=libmtwist.a
LIBMTWIST_SOURCES=mt.c seed.c
LIBMTWIST_OBJS=$(LIBMTWIST_SOURCES:.c=.o)

TESTS=mttest
TEST_SOURCES=test.o
TEST_OBJS=$(TEST_SOURCES:.c=.o)

CFLAGS=-g
LDFLAGS=-g

CPPFLAGS=-DHAVE_STDINT_H -DHAVE_STDLIB_H -DHAVE_UNISTD_H -DHAVE_TIME_H -I.

all: $(TESTS)

test check: mttest
	./mttest

mttest: $(LIBMTWIST) test.o
	$(CC) -o $@ test.o $(LIBMTWIST)

$(LIBMTWIST): $(LIBMTWIST_OBJS)
	$(RM) $@
	$(AR) -cq $@ $(LIBMTWIST_OBJS)

clean:
	$(RM) $(TESTS) $(TEST_OBJS) $(LIBMTWIST) $(LIBMTWIST_OBJS)
